# Generated by Django 5.1.2 on 2024-10-24 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0001_initial'),
        ('ServiceCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('specific_problems', models.TextField(default='No specific problems mentioned')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.servicecenter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authenticate.userdata')),
            ],
        ),
    ]
