# Generated by Django 5.1 on 2024-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='image',
            field=models.ImageField(default='article_images/default.png', upload_to='article_images/'),
        ),
    ]
