# Generated by Django 5.1 on 2024-10-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_artikel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
