# Generated by Django 5.1 on 2024-12-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_remove_artikel_image_artikel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
