# Generated by Django 5.1.2 on 2024-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserForum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='discussion_id',
            new_name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='last_reply',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
