# Generated by Django 5.1.2 on 2024-10-26 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserForum', '0002_rename_discussion_id_reply_discussion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='time_sent',
        ),
        migrations.AddField(
            model_name='reply',
            name='replied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
