# Generated by Django 5.1.2 on 2024-10-26 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserForum', '0003_remove_reply_date_remove_reply_time_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
