# Generated by Django 5.1.1 on 2024-10-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sim', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GamingConsole',
        ),
        migrations.DeleteModel(
            name='Headphone',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='MobilePhone',
        ),
        migrations.DeleteModel(
            name='Tablet',
        ),
        migrations.DeleteModel(
            name='Television',
        ),
        migrations.DeleteModel(
            name='Wearable',
        ),
    ]
