# Generated by Django 5.1.1 on 2024-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_smartphone_delete_gamingconsole_delete_headphone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('screen_size_inches', models.FloatField()),
                ('camera_mp', models.CharField(max_length=100)),
                ('battery_capacity_mAh', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
