# Generated by Django 5.1.1 on 2024-10-24 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_phone_delete_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
