# Generated by Django 5.1.1 on 2024-10-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
