# Generated by Django 5.1.1 on 2024-10-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_phone_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
