# Generated by Django 5.1.1 on 2024-10-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_alter_phone_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='is_favorite',
        ),
    ]
