# Generated by Django 5.1.1 on 2024-10-26 03:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_phone_five_star_phone_four_star_phone_one_star_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phone',
            index=django.contrib.postgres.indexes.GinIndex(fields=['brand', 'model'], name='Homepage_ph_brand_e7a903_gin'),
        ),
    ]
