# Generated by Django 5.1.1 on 2024-10-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailProduct', '0002_alter_review_product_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
