# Generated by Django 5.1.1 on 2024-10-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_alter_userdata_profile_picture'),
        ('Authenticate', '0002_userdata_favorite_phones'),
    ]

    operations = [
    ]
