# Generated by Django 5.1.2 on 2024-10-24 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('picture_url', models.URLField(max_length=500)),
                ('battery_capacity_mAh', models.IntegerField()),
                ('price_inr', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
